---
name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test (${{ matrix.os }}, ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, beta]
        experimental: [false]
        include:
          - os: ubuntu-latest
            rust: nightly
            experimental: true
          - os: windows-latest
            rust: nightly
            experimental: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --verbose

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy
        run: cargo clippy -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Format check
        run: cargo fmt -- --check

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build documentation
        run: cargo doc --verbose --no-deps
